export enum EducationModuleType {
  NUTRITION = 'NUTRITION',
  EXERCISE = 'EXERCISE',
  MENTAL_HEALTH = 'MENTAL_HEALTH',
  CHILDBIRTH_PREPARATION = 'CHILDBIRTH_PREPARATION',
  PREGNANCY = 'PREGNANCY',
}
